apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: MTIzNA== 
    username: YWRtaW4= 
  template:
    metadata:
      name: db-creds
      namespace: default